# Generated by Django 4.2.19 on 2025-02-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='bio',
        ),
        migrations.DeleteModel(
            name='First',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
