# Generated by Django 3.2.5 on 2021-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
