# Generated by Django 3.2.5 on 2021-07-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_auto_20210727_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
