# Generated by Django 3.2.5 on 2021-07-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0011_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, default='media/noname_c2gjcn.jpg', upload_to='avatar/'),
        ),
    ]
