# Generated by Django 3.2.5 on 2021-09-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0020_first_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first', to='gram.first'),
        ),
    ]
