# Generated by Django 3.2.5 on 2021-09-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0022_alter_main_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fff', to='gram.first'),
        ),
    ]
