# Generated by Django 3.2.5 on 2021-09-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0023_alter_main_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('bio2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='qqq', to='gram.first')),
            ],
        ),
    ]
