# Generated by Django 3.2.5 on 2021-10-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0025_first_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('create_post', 'Can create post'),), 'verbose_name': 'post'},
        ),
    ]
